default:
  image:
    # You made a change inside the image, uncomment this line and comment the one with :branch-development to test your image on your branch ;):
    #name: $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_SLUG
    name: $CI_REGISTRY_IMAGE:branch-compose
  before_script:
    # We must keep these variables here. We can't do it inside the entrypoint, as idk how but
    # gitlab is going to convert them as a variable content instead of a variable file...
    - base64 -d - < "$PROTON_KEY_FILE2" > app/protonkey.jks
    - base64 -d -  < "$SERVICE_ACCOUNT_FILE" > app/service_account.json
    - md5sum app/protonkey.jks
    - md5sum app/service_account.json
    - base64 -d - < "$GRADLE_PROPERTIES_FILE2" > gradle.properties
    - git fetch origin development

variables:
  GIT_FETCH_EXTRA_FLAGS: --tags

stages:
  - image
  - analyze
  - build
  - startReview
  - test
  - report
  - bot
  - mirror
  - publish



########## Manage the Image ##########
.common-image:
  cache: {}
  stage: image
  image: $CI_REGISTRY/infra/kubernetes/images/docker:stable
  tags:
    - medium
  interruptible: true
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - name: $CI_REGISTRY/infra/kubernetes/images/docker:dind
      alias: docker
  before_script:
    - apk update
    - apk add make bash
  except:
    - schedules
    - triggers
  script:
    - make image branch=$CI_COMMIT_REF_SLUG


# Make image when we push to a branch -> run tests on top of this one
create-ci-image-auto:
  extends: .common-image
  only:
    refs:
      - development
    changes:
      - entrypoint
      - Dockerfile

# If we want to force regenerate the image
create-ci-image-manual:
  when: manual
  extends: .common-image

# Once the CI is green, we retag the current branch-development to latest
create-ci-image-latest:
  stage: publish
  extends: create-ci-image-auto
  tags:
    - small
  dependencies: [] # Prevent download + extract artifacts
  only:
    - development
  script:
    - make latest

cache:
  - key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - .gradle

  - key: ${CI_COMMIT_SHORT_SHA}
    policy: pull
    paths:
      - '**/build/tmp/'

detekt analysis:
  stage: analyze
  image: $CI_REGISTRY_IMAGE:latest
  cache:
    - key: $CI_COMMIT_REF_SLUG
      policy: pull-push
      paths:
        - .gradle
  tags:
    - small
  script:
    - ./gradlew detekt
  artifacts:
    expire_in: 4 weeks
    reports:
      codequality: app/build/reports/detekt.json

build debug:
  stage: build
  cache:
    - key: $CI_COMMIT_REF_SLUG
      policy: pull
      paths:
        - .gradle

    - key: ${CI_COMMIT_SHORT_SHA}
      policy: push
      paths:
        - '**/build/tmp/'

  tags:
    - large
  script:
    - ./gradlew assembleDirectDebug
    - ./gradlew assembleDirectDebugAndroidTest
    - export ARCHIVES_BASE_NAME=$(./gradlew -q getArchivesName | tail -n 1)
    - echo ${ARCHIVES_BASE_NAME}
    - echo "ARCHIVES_BASE_NAME=${ARCHIVES_BASE_NAME}" > deploy.env
  artifacts:
    expire_in: 1 week
    paths:
    - app/build/outputs/apk
    reports:
      dotenv: deploy.env

build black:
  stage: build
  tags:
    - large
  script:
    - ./gradlew assembleBlackDebug
  when: manual
  artifacts:
    expire_in: 1 week
    paths:
    - app/build/outputs/apk

build google play release:
  stage: build
  except:
    - master
  tags:
    - large
  script:
    - ./gradlew openvpn:assemble
    - ./gradlew assembleGooglePlayRelease -PabiSplit -PbuildUniversalApk
  when: manual
  artifacts:
    expire_in: 1 week
    paths:
    - app/build/outputs/apk

build release (auto):
  stage: build
  only:
    refs:
      - master
  tags:
    - large
  script:
    - ./gradlew openvpn:assemble
    - ./gradlew assembleDirectRelease -PabiSplit -PbuildUniversalApk
  artifacts:
    expire_in: 3 week
    paths:
      - app/build/outputs/apk

unit tests:
  stage: test
  tags:
    - large
  script:
    - ./gradlew testDirectDebug

.firebase_authenticate_script: &firebase_authenticate_script
    - export ARCHIVES_BASE_NAME=$(./gradlew -q getArchivesName | tail -n 1)
    - echo ${ARCHIVES_BASE_NAME}
    - echo $CLOUD_PROJECT_ID
    - gcloud config set project $CLOUD_PROJECT_ID
    - echo "$SERVICE_ACCOUNT" > /tmp/service-account.json
    - gcloud auth activate-service-account --key-file /tmp/service-account.json
    - APP="$APP_LOCATION"${ARCHIVES_BASE_NAME}-${APP_TYPE}
    - TEST_APP="$TEST_APP_LOCATION"${ARCHIVES_BASE_NAME}-${TEST_APP_TYPE}
    - echo $APP
    - echo $TEST_APP
    - echo $PWD

.tests_preparation_script: &tests_preparation_script
  stage: test
  tags:
    - small
  script:
    - *firebase_authenticate_script
    - gcloud firebase test android
        run firebase-device-config.yml:${TESTS_TYPE}
        --app "$APP"
        --test "$TEST_APP"
        --num-flaky-test-attempts=2
        --environment-variables coverage=true,coverageFile="/sdcard/$COVERAGE_FILE_NAME.ec",listener=com.protonvpn.testsHelper.ToastingRunListener
        --directories-to-pull /sdcard
        --test-targets "class $TEST_SUITE"
    - coverageFile=`gsutil ls gs://test-lab-5w5jc16j2t3nz-wzxvv7m6j0vt6/**/$COVERAGE_FILE_NAME.ec | tail -1`
    - gsutil cp $coverageFile app/build/outputs/apk | true
  artifacts:
    expire_in: 1 week
    paths:
    - app/build/outputs/apk

firebase quick tests:
  <<: *tests_preparation_script
  variables:
    TESTS_TYPE: quickTest
    APP_LOCATION: "app/build/outputs/apk/direct/debug/"
    APP_TYPE: "direct-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/direct/debug/"
    TEST_APP_TYPE: "direct-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.MobileSuite"
    COVERAGE_FILE_NAME: "coverageMobile.ec"

firebase full tests:
  <<: *tests_preparation_script
  variables:
    TESTS_TYPE: fullTest
    APP_LOCATION: "app/build/outputs/apk/direct/debug/"
    APP_TYPE: "direct-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/direct/debug/"
    TEST_APP_TYPE: "direct-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.MobileSuite"
    COVERAGE_FILE_NAME: "coverageMobileFull.ec"
  when: manual

firebase tv tests:
  <<: *tests_preparation_script
  variables:
    TESTS_TYPE: tvTest
    APP_LOCATION: "app/build/outputs/apk/direct/debug/"
    APP_TYPE: "direct-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/direct/debug/"
    TEST_APP_TYPE: "direct-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.TvSuite"
    COVERAGE_FILE_NAME: "coverageTv.ec"

firebase real connection tests:
  <<: *tests_preparation_script
  variables:
    TESTS_TYPE: realConnectionTest
    APP_LOCATION: "app/build/outputs/apk/direct/debug/"
    APP_TYPE: "direct-debug.apk"
    TEST_APP_LOCATION: "app/build/outputs/apk/androidTest/direct/debug/"
    TEST_APP_TYPE: "direct-debug-androidTest.apk"
    TEST_SUITE: "com.protonvpn.testSuites.RealConnectionSuite"
    COVERAGE_FILE_NAME: "coverageRealConnection.ec"

firebase robo tests:
  stage: test
  tags:
    - small
  script:
    - *firebase_authenticate_script
    - gcloud firebase test android run
      --type robo
      --app "$APP"
      --device model=Pixel3,version=30,locale=en,orientation=portrait
      --timeout 300s
  variables:
    APP_LOCATION: "app/build/outputs/apk/direct/debug/"
    APP_TYPE: "direct-debug.apk"

coverage report:
  stage: report
  tags:
    - large
  script:
    - ./gradlew jacocoTestReport
    - ./gradlew coverageReport
    - python3 jacocoConverter.py app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml app/src/main/java > app/build/reports/cobertura-coverage.xml
  allow_failure: true
  artifacts:
    expire_in: 1 week
    paths:
      - app/build/reports
    reports:
      cobertura: app/build/reports/cobertura-coverage.xml

owasp check:
  stage: report
  tags:
    - large
  script:
    - ./gradlew dependencyCheckAggregate
  when: manual
  artifacts:
    expire_in: 1 week
    paths:
      - build/reports

sync-app:
  cache: {}
  stage: mirror
  only:
    refs:
      - master

  script:
    # Clone instead of using the current CI as it creates the error (shallow update not allowed)
    - git clone "$CI_REPOSITORY_URL" --branch master _APP_CLONE;
    - cd _APP_CLONE
    - git remote add public $PUBLIC_REPO_URL
    - git push public master
    # Push the latest tag we can find
    - git push public "$(git describe --abbrev=0)"

publish-apk-internal:
  stage: publish
  tags:
    - large
  only:
    refs:
      - development
  script:
    - ./gradlew openvpn:assemble
    - ./gradlew publishInternal -PabiSplit

startReview:
  before_script:
    - export REVIEW_APP_ARTIFACT_PATH="app/build/outputs/apk/direct/debug/"${ARCHIVES_BASE_NAME}-direct-debug.apk
    - echo ${REVIEW_APP_ARTIFACT_PATH}
  extends: .startReview

stopReview:
  before_script: []
  extends: .stopReview

include:
  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'

  - project: 'agarroux/publish-github'
    ref: master
    file: '/jobs/release.gitlab-ci.yml'

  - local: '/appetize-integration.yml'

i18n-sync-crowdin:
  variables:
      I18N_SYNC_BRANCH: development
      I18N_SYNC_CROWDIN_PROJECT: 'android-vpn'
  extends: .i18n-sync-crowdin-shared

i18n-commit-locales:
  variables:
      I18N_COMMIT_BRANCH_PUSH: development
      I18N_COMMIT_BRANCH_ALLOWED: development
      I18N_COMMIT_CROWDIN_PROJECT: 'android-vpn'
  extends: .i18n-commit-locales-shared

publish-github:
  stage: publish
  only:
    refs:
      - master
  variables:
    RELEASE_APP: android-vpn
    RELEASE_GITHUB_REPOSITORY: $PUBLIC_REPO_URL
  extends: .release-make-release
